name: PR Testing s390x

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths: ['src/**','test/**','project.clj']

jobs:
  pr-testing:
    name: PR Testing
    strategy:
      fail-fast: false
      matrix:
        javaargs: ['with-profile fips', '']
        filter: [':singlethreaded', ':multithreaded']
        version: ['11', '17']
    runs-on: ubuntu-24.04-s390x
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
      - name: install ruby 3.1 and bundler
        run: |
          wget https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.5.tar.gz
          tar -xzf ruby-3.1.5.tar.gz
          cd ruby-3.1.5
          ./configure --prefix=$HOME/ruby-3.1 --disable-install-doc
          make -j$(nproc)
          make install
          export PATH="$HOME/ruby-3.1/bin:$PATH"
          echo "$HOME/ruby-3.1/bin" >> $GITHUB_PATH
          ruby -v
          gem install bundler
      - name: install lein
        run: |
          wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          sudo mv lein /usr/bin/
      - name: setup gems
        run: ./dev-setup
      - name: clojure tests
        run: |
          export JAVA_TOOL_OPTIONS="-Duser.timezone=UTC"
          lein -U ${{ matrix.javaargs }} test ${{ matrix.filter }}
        timeout-minutes: 120
      - name: rspec tests
        run: rake spec
